# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18irEhb_5rOo_ZKgCttblh15G2AlzHjFl
"""

!pip install ucimlrepo

import pandas as pd
from ucimlrepo import fetch_ucirepo

print("Fetching dataset from UCI Repository...")

# Fetch the Student Dropout and Academic Success dataset (ID 697)
dataset = fetch_ucirepo(id=697)

# Split into features (X) and target (y)
X = dataset.data.features
y = dataset.data.targets

# Preview the data
print("Successfully loaded!")
print(f"Features shape: {X.shape}")
display(X.head()) # Use display() in Colab for a pretty table

# 1. Check for missing values
print("Missing values in features:", X.isnull().sum().sum())

# 2. Let's look at the target distribution
print("\nOriginal Target Distribution:")
print(y['Target'].value_counts())

# 3. Create a binary target: 1 if 'Dropout', 0 if 'Graduate' or 'Enrolled'
# This simplifies 'Risk' vs 'No Risk'
y_binary = y['Target'].apply(lambda x: 1 if x == 'Dropout' else 0)

print("\nNew Binary Target Distribution (1 = At Risk, 0 = Safe):")
print(y_binary.value_counts())

# 4. Feature Selection: Let's see the column names we have to work with
print("\nAvailable Features:")
print(X.columns.tolist())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Split the data into Training and Testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.2, random_state=42)

# 2. Initialize and Train the Random Forest
print("Training the model... please wait.")
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 3. Evaluate the model
y_pred = model.predict(X_test)

print("\n--- Model Performance ---")
print(classification_report(y_test, y_pred))

# 4. Look at which features actually matter
import numpy as np
import matplotlib.pyplot as plt

importances = model.feature_importances_
indices = np.argsort(importances)[-10:]  # Top 10 features

plt.figure(figsize=(10,6))
plt.title('Top 10 Most Important Features for Predicting Risk')
plt.barh(range(len(indices)), importances[indices], align='center')
plt.yticks(range(len(indices)), [X.columns[i] for i in indices])
plt.xlabel('Relative Importance')
plt.show()

import joblib

# 1. Save the model to a file
joblib.dump(model, 'student_risk_model.pkl')
print("Model saved as 'student_risk_model.pkl'")

# 2. Save the feature names (we'll need these for the dashboard)
feature_names = X.columns.tolist()
joblib.dump(feature_names, 'feature_names.pkl')
print("Feature names saved as 'feature_names.pkl'")

# 3. Create a 'Sample' prediction function to test
def predict_student_risk(sample_data):
    # Load model
    loaded_model = joblib.load('student_risk_model.pkl')

    # Get probability
    probability = loaded_model.predict_proba(sample_data)[0][1]

    # Return interpretation
    if probability > 0.7:
        risk_level = "High"
    elif probability > 0.4:
        risk_level = "Medium"
    else:
        risk_level = "Low"

    return risk_level, probability

# Test with a row from our test set
test_row = X_test.iloc[[0]]
level, score = predict_student_risk(test_row)

print(f"\nTest Prediction:")
print(f"Risk Level: {level}")
print(f"Risk Score: {score:.2f}")

